[package]
name = "InterestMath"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
license = "MIT"           # e.g., "MIT", "GPL", "Apache 2.0"
authors = ["Jose Cerqueira (jose@interestprotocol.com)"]     

[dependencies]

[addresses]
interest_math = "0x0"